export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const ADD_EMPLOYEES = 'ADD_EMPLOYEES';
export const UPDATE_EMPLOYEES = 'UPDATE_EMPLOYEES';
export const EDIT_EMPLOYEES = 'EDIT_EMPLOYEES';
export const DELETE_EMPLOYEES = 'DELETE_EMPLOYEES';
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS';
export const DELETE_DEPARTMENTS = 'DELETE_DEPARTMENTS';
export const EDIT_DEPARTMENTS = 'EDIT_DEPARTMENTS';
export const SEARCH = 'SEARCH';

